# Generated by Django 6.0 on 2025-12-31 00:51

import rejs.modele.pola
from django.db import migrations, models


def fix_unknown_values(apps, schema_editor):
	"""Zamienia wartości 'unknown' i '00-000' na puste stringi."""
	Zgloszenie = apps.get_model("rejs", "Zgloszenie")
	Zgloszenie.objects.filter(adres="unknown").update(adres="")
	Zgloszenie.objects.filter(miejscowosc="unknown").update(miejscowosc="")
	Zgloszenie.objects.filter(kod_pocztowy="00-000").update(kod_pocztowy="")


class Migration(migrations.Migration):
	dependencies = [
		("rejs", "0022_audit_log"),
	]

	operations = [
		# Najpierw napraw dane, potem zmień schemat
		migrations.RunPython(fix_unknown_values, migrations.RunPython.noop),
		migrations.AlterModelOptions(
			name="dane_dodatkowe",
			options={
				"permissions": [
					(
						"export_sensitive_data",
						"Może eksportować dane wrażliwe do raportów",
					)
				],
				"verbose_name": "Dane dodatkowe",
				"verbose_name_plural": "Dane dodatkowe",
			},
		),
		migrations.AlterField(
			model_name="dane_dodatkowe",
			name="poz1",
			field=rejs.modele.pola.EncryptedTextField(default="12345678900", max_length=13, verbose_name="PESEL"),
		),
		migrations.AlterField(
			model_name="dane_dodatkowe",
			name="poz2",
			field=rejs.modele.pola.EncryptedTextField(
				choices=[
					("paszport", "paszport"),
					("dowod-osobisty", "dowód osobisty"),
				],
				default="paszport",
				max_length=14,
				verbose_name="Typ dokumentu",
			),
		),
		migrations.AlterField(
			model_name="dane_dodatkowe",
			name="poz3",
			field=rejs.modele.pola.EncryptedTextField(default="ABC123", verbose_name="Numer dokumentu"),
		),
		migrations.AlterField(
			model_name="dane_dodatkowe",
			name="zgoda_dane_wrazliwe",
			field=models.BooleanField(
				default=False,
				help_text="Wyrażam zgodę na przetwarzanie moich danych osobowych (PESEL, numer dokumentu) w celu realizacji procedur zaokrętowania zgodnie z wymogami kapitana. Dane zostaną usunięte w ciągu 30 dni po zakończeniu rejsu.",
				verbose_name="Zgoda na przetwarzanie danych wrażliwych",
			),
		),
		migrations.AlterField(
			model_name="rejs",
			name="aktywna_rekrutacja",
			field=models.BooleanField(default=True, verbose_name="Aktywna rekrutacja"),
		),
		migrations.AlterField(
			model_name="rejs",
			name="do",
			field=models.DateField(verbose_name="Data do"),
		),
		migrations.AlterField(
			model_name="rejs",
			name="koniec",
			field=models.CharField(max_length=200, verbose_name="Port końcowy"),
		),
		migrations.AlterField(
			model_name="rejs",
			name="od",
			field=models.DateField(verbose_name="Data od"),
		),
		migrations.AlterField(
			model_name="rejs",
			name="start",
			field=models.CharField(max_length=200, verbose_name="Port początkowy"),
		),
		migrations.AlterField(
			model_name="wplata",
			name="rodzaj",
			field=models.CharField(
				choices=[("wplata", "Wpłata"), ("zwrot", "Zwrot")],
				default="wplata",
				max_length=7,
			),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="adres",
			field=models.CharField(default="", verbose_name="Adres"),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="data_urodzenia",
			field=models.DateField(verbose_name="Data urodzenia"),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="kod_pocztowy",
			field=models.CharField(default="", verbose_name="Kod pocztowy"),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="miejscowosc",
			field=models.CharField(default="", verbose_name="Miejscowość"),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="obecnosc",
			field=models.CharField(
				choices=[("tak", "tak"), ("nie", "nie")],
				max_length=3,
				verbose_name="Uczestnictwo w Zobaczyć Morze",
			),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="rodo",
			field=models.BooleanField(
				help_text="Zgadzam się na przetwarzanie danych osobowych zgodnie z polityką prywatności Zobaczyć Morze.",
				verbose_name="Zgoda na przetwarzanie danych osobowych",
			),
		),
		migrations.AlterField(
			model_name="zgloszenie",
			name="wzrok",
			field=models.CharField(
				choices=[
					("WIDZI", "widzący"),
					("NIEWIDOMY", "niewidomy"),
					("SLABO-WIDZACY", "słabo widzący"),
				],
				default="WIDZI",
				max_length=15,
				verbose_name="Status wzroku",
			),
		),
	]
